locations/urls.py
from django.conf.urls.defaults import patterns, include, url
from .ajax_submit_form import submit_form
from .forms import ProfileSettingsForm, ProfileForm
from .views import save_profile_settings, save_profile


urlpatterns = patterns('locations.views',
)

profiles/urls.py
from django.conf.urls.defaults import patterns, include, url
from .ajax_submit_form import submit_form
from .forms import ProfileSettingsForm, ProfileForm
from .views import save_profile_settings, save_profile


urlpatterns = patterns('profiles.views',
    url(r'^edit/$', 'edit_profile', name='edit_profile'),
    url(r'^view/(?P<slug>\w{32})/', 'view_profile', name='view_profile'),

    url(r'^upload_photo/$', 'upload_photo', name='upload_photo'),
    url(r'^send_message/$', 'send_message'),
    # AJAX URLS
    url(r'^save_settings/$', submit_form,
        {'form_class': ProfileSettingsForm,
        'callback': lambda request, *args, **kwargs: { },
        'complete_func': save_profile_settings,
        }, name='save_settings'),
    url(r'^save_profile/$', submit_form,
        {'form_class': ProfileForm,
         'callback': lambda request, *args, **kwargs: { },
        'complete_func': save_profile,
        }, name='save_profile'),

    url(r'change_location/', 'change_location', name='change_location'),
    url(r'^change_safe_mode/$', 'change_safe_mode', name='change_safe_mode'),
    url(r'^images/set_primary/(?P<slug>\w{32})/?', 'set_primary_avatar', name='set_primary_avatar'),
    url(r'^update/delete/(?P<slug>\w{32})/?', 'delete_update', name='delete_update'),
    url(r'^notifications/', include('notification.urls')),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf import settings
from xcp_registration.views import register
from xcp_registration.forms import RegistrationFormStep1  #, AuthForm
import autocomplete_light
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import login
from profiles.ajax_submit_form import submit_form
from xcp_registration.views import ajax_login
import django


admin.autodiscover()
# enable autocomplete
autocomplete_light.autodiscover()

urlpatterns = patterns('',

    url(r'^$', 'profiles.views.index', name='index'),
    #url(r'^saving_message/', 'profiles.views.save_message'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/', include('profiles.urls')),
    url(r'^visits/', include('user_statistic.urls')),
    url(r'^search/', 'profiles.views.search', name='search'),
    url(r'^helpdata/', 'profiles.views.helpdata', name = 'helpdata' ),
    url(r'^subscribe_user/', 'subscribe.views.subscribe_user', name = 'subscribe_user'),
    url(r'^subscribe/', 'subscribe.views.subscribe', name = 'subscribe'),
    url(r'^datingCenter/', 'profiles.views.datingcenter', name = 'datingcenter'),
    url(r'^getUpdateData/', 'profiles.views.getUpdateData', name = 'getUpdateData'),
    url(r'^getMessageData/', 'profiles.views.getMessageData', name = 'getMessageData'),
    url(r'^getviewed/','user_statistic.views.get_viewed_widget', name = 'viewed_widget'),
    url(r'^getlikes/','user_statistic.views.get_likes_widget', name = 'likes_widget'),
    url(r'^getonline','user_statistic.views.get_online_widget', name = 'online_widget'),
    url(r'^postupdate','profiles.views.post_update', name = 'postupdate'),
    url(r'^check_payment','subscribe.views.check_payment', name = 'check_payment'),
    url(r'^getlast','user_statistic.views.get_registered_widget', name = 'get_last'),
    url(r'^delete_message/(?P<s_id>\w{32})/?', 'profiles.views.delete_message', name = 'delete_message'),
    url(r'^set_img/', 'profiles.views.set_img', name = 'set_img'),
    url(r'^del_img/', 'profiles.views.del_img', name = 'del_img'),
    url(r'^get_more/', 'profiles.views.get_more', name = 'get_more'),
    url(r'^matchProcess', 'profiles.views.match_process', name = 'match_process'),
    url(r'^get_sign_up', 'xcp_registration.views.get_sign_up', name = 'get_sign_up'),


    #url(r'^auth/login/$', submit_form,
        #{'form_class': AuthenticationForm,
         #'callback': lambda request, *args, **kwargs: { },
        #'complete_func': login,
        #}, name='auth_login'),

    url(r'^auth/login/$', submit_form,
        {'complete_func':ajax_login,
            'form_class':AuthenticationForm,
            'callback':lambda *args, **kwargs: { },
            }, name='auth_login'),
    url(r'^auth/logout','django.contrib.auth.views.logout', name='logout'),
    url(r'^auth/ajax_logout/?$', 'xcp_registration.views.sign_out',
        name='ajax_logout'),
    url(r'^auth/ajax_password_reset/', submit_form,
        {'complete_func': django.contrib.auth.views.password_reset,
         'form_class': django.contrib.auth.forms.PasswordResetForm,
         'callback': lambda *a, **k: {},
        }, name="password_reset"),
    url(r'^auth/', include('django.contrib.auth.urls')),

    url(r'^registration/', include('xcp_registration.urls')),

    #url(r'^my_admin/jsi18n', 'django.views.i18n.javascript_catalog'),
    url(r'^captcha/', include('captcha.urls')),

    # cities auto complete
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^messages/', include('messages.urls')),


)
urlpatterns += staticfiles_urlpatterns()



if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        url(r'^site_media/media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

locations/models.py
from django.db import models, connection
from cities_light.models import City
from django.conf import settings
from profiles.models import Profile


'''
Code is never used in projec
'''
class SearchManager(models.Manager):
    def get_all_in_radius(self, lat, lng, distance=0):
        try:
            cursor = connection.cursor()
            cursor.execute(
                """SELECT id FROM %s
                WHERE DISTANCE(latitude, longitude, %s, %s) < %f;""" % (
                    self.models._meta.db_table,
                    lat, lng, getattr(settings, "LOCATION_RADIUS", float(distance))
                ))
            return [i[0] for i in cursor.fetchall()]
        except Exception as e:
            print e
            return list()



class LocationSearchModel(models.Model):
    search = SearchManager()

    class Meta:
        abstract = True

class Location(City, LocationSearchModel):
    class Meta:
        proxy = True
'''
End of never used code
'''

def get_all_in_radius(lat, lng, distance=0):
    try:
        cursor = connection.cursor()
        cursor.execute(
            """SELECT id FROM %s
            WHERE DISTANCE(latitude, longitude, %s, %s) < %f;""" % (
                City._meta.db_table,
                lat, lng, getattr(settings, "LOCATION_RADIUS", float(distance))
            ))
        return [i[0] for i in cursor.fetchall()]
    except Exception as e:
        print e
        return list()

def filter_users(lat=0, lng=0, city=None):
    if city and isinstance(city, City):
        lat, lng = city.latitude ,city.longitude
    cities = get_all_in_radius(lat=lat, lng=lng)
    return Profile.objects.filter(location__id__in=cities)

profiles/models.py
import hashlib
import random
import datetime
from os import path
from django.db import models
from django.contrib.auth.models import User, UserManager
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.conf import settings
from sorl.thumbnail import get_thumbnail
from sorl.thumbnail import ImageField
#from subscribe.models import Subscribe
try:
    from notification import models as notification
except ImportError:
    notification = None

from .utils import datetime_to_epoch
#from locations.models import XCity
from cities_light.models import City


DEFAULT_ABOUT_ME = getattr(settings, 'DEFAULT_ABOUT_ME', 'Some simple text')


class Image(models.Model):
    '''This class represents user's avatar and all user's photos.
    hash - is 32 characters length string.
    first 16 chars - md5(self.id) - defines foolder name,
    next 16 - md5(self.upload_date as timestamp) - is file name.
    '''
    UPLOAD_TO = "images"

    def _get_hash(self):
        if not self.upload_date:
            self.upload_date = datetime.datetime.now()
        hsh = hashlib.md5(unicode(self.user.id))
        hsh.update(unicode(int(datetime_to_epoch(self.upload_date))))
        return hsh.hexdigest()


    def get_path(self, name):
        hsh = self._get_hash()
        extension = name.split('.')[-1]
        f_name = "." + extension
        self.slug = hsh
        return path.join(self.UPLOAD_TO, hsh[0:2], hsh[2:4] , hsh+f_name)

    slug = models.CharField(max_length=32, unique=True, db_index=True)
    is_avatar = models.BooleanField(default=False)
    is_safe = models.BooleanField(default=False)
    need_moderation = models.BooleanField(default=True)
    src = ImageField(verbose_name='', upload_to=get_path)
    upload_date = models.DateField(auto_now_add=True, auto_now=True)
    user = models.ForeignKey('Profile')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_hash()
        super(Image, self).save(*args, **kwargs)


class ProfileManager(UserManager):
    def create_user(self, email, password=None, **required_fields):
        now = datetime.datetime.now()
        # create unique username
        import re
        re_name = r'^(?P<name>\w*?)(?P<count>\d+$)'  #r'^(?P<name>\D*)(?P<count>\d+?$)'
        username = email.split("@")[0]
        not_uniq = lambda uname: bool(self.model.objects.filter(username=uname).count())
        while not_uniq(username):
            match = re.match(re_name, username)
            if match:
                id = int(match.group("count"))
                id += 1
                username = "{}{}".format(match.group("name"), id)
            else:
                username = "{}{}".format(username, 1)

        hsh = hashlib.md5(unicode(datetime_to_epoch(datetime.datetime.now())))
        hsh.update(unicode(random.randint(1, 10**9)))
        required_fields.setdefault('slug', hsh.hexdigest())
        # maybe I need to filter **required_fields

        # Normalize the address by lowercasing the domain part of the email
        # address.
        try:
            email_name, domain_part = email.strip().split('@', 1)
        except ValueError:
            pass
        else:
            email = '@'.join([email_name, domain_part.lower()])

        user = self.model(username=username, email=email, is_staff=False,
                         is_active=True, is_superuser=False, last_login=now,
                         last_active = now,
                         date_joined=now, **required_fields)

        user.set_password(password)
        user.save(using=self._db)
        return user


class Profile(User):
    '''This class represents user's profile'''
    NOTIFICATION_CHOICES = (
        (0, 'No'),
        (1, 'Instant'),
        (2, 'Digest'),
    )
    EMAIL_VIEWS = (
        (0, 'No email notifications'),
        (1, 'Recieve emeail notification'),
    )
    THIRD_PARTY_EMAIL = (
        (0, 'No email notification'),
        (1, 'Recieve email notification'),
    )
    GENDER_CHOICES = (
        (0, 'Man'),
        (1, 'Woman'),
    )
    HEIGHT_CHOICES = (
        (0, "Prefer not to say"),
        (1, "&lt; 5 ft 0 in / &lt; 152 cm"),
        (2, "5 ft 0 in / 153-155 cm"),
        (3, "5 ft 1 in / 156-157 cm"),
        (4, "5 ft 2 in / 158-160 cm"),
        (5, "5 ft 3 in / 161-162 cm"),
        (6, "5 ft 4 in / 163-165 cm"),
        (7, "5 ft 5 in / 166-167 cm"),
        (8, "5 ft 6 in / 168-170 cm"),
        (9, "5 ft 7 in / 171-172 cm"),
        (10, "5 ft 8 in / 173-175 cm"),
        (11, "5 ft 9 in / 176-178 cm"),
        (12, "5 ft 10 in / 179-180 cm"),
        (13, "5 ft 11 in / 181-183 cm"),
        (14, "6 ft 0 in / 184-185 cm"),
        (15, "6 ft 1 in / 186-188 cm"),
        (16, "6 ft 2 in / 189-190 cm"),
        (17, "6 ft 3 in / 191-193 cm"),
        (18, "6 ft 4 in / 194-195 cm"),
        (19, "&gt; 6 ft 4 in / &gt; 195 cm"),
    )

    RACE_CHOICES = (
        (1, "Prefer not to say"),
        (2, "American Indian"),
        (3, "Asian"),
        (4, "Black"),
        (5, "Caucasian"),
        (6, "East Indian"),
        (7, "Hispanic"),
        (8, "Middle Eastern"),
        (9, "Various"),
        (10, "Other"),
    )

    RELIGION_CHOICES = (
        (1, "Prefer not to say"),
        (2, "Agnostic"),
        (3, "Atheist"),
        (4, "Buddhist/Taoist"),
        (5, "Catholic"),
        (6, "Hindu"),
        (7, "Islamic"),
        (8, "Jewish"),
        (9, "Protestant"),
        (10, "Spiritual"),
        (11, "Other"),
    )
    HAIR_COLOR_CHOICES = (
        (1, "Prefer not to say"),
        (2, "Black"),
        (3, "Brown"),
        (4, "Blond"),
        (5, "Auburn"),
        (6, "Red"),
        (7, "Gray"),
    )
    EYE_COLOR_CHOICES = (
        (1, "Prefer not to say"),
        (2, "Amber"),
        (3, "Blue"),
        (4, "Brown"),
        (5, "Gray"),
        (6, "Green"),
        (7, "Hazel"),
        (8, "Red"),
    )
    BODY_CHOICES = (
        (1, "Prefer not to say"),
        (2, "Average"),
        (3, "Slim"),
        (4, "Athletic"),
        (5, "Ample"),
        (6, "A little extra padding"),
        (7, "Large"),
    )
    PROFESSION_CHOICES = (
        (1, "Prefer not to say"),
        (2, "Not Working"),
        (3, "Student"),
        (4, "Engineering/Technical"),
        (5, "Business (Management)"),
        (6, "Clerical (Office/Shop)"),
        (7, "Design (Architect/Fashion)"),
        (8, "Education"),
        (9, "Government (Office/Shop)"),
        (10, "Other"),
        (11, "Medical (Nursing/Physician)"),
    )
    # location fields
    location = models.ForeignKey(City, blank=True, null=True)
    #lat = models.FloatField()
    #lng = models.FloatField()

    # slug = hash
    slug = models.SlugField(max_length=32)

    name = models.CharField(max_length=50)

    # settings fields
    email_notifications = models.IntegerField(
        choices=NOTIFICATION_CHOICES, default=1)
    email_profile_views = models.IntegerField(choices=EMAIL_VIEWS, default=1)
    third_party_email = models.IntegerField(choices=THIRD_PARTY_EMAIL,
                                            default=1)
    #Profile fields
    about_me = models.TextField("", blank=True)
    looking_for = models.IntegerField(choices=GENDER_CHOICES, default=1)
    height = models.IntegerField(choices=HEIGHT_CHOICES, default=0)
    race = models.IntegerField(choices=RACE_CHOICES, default=0)
    religion = models.IntegerField(choices=RELIGION_CHOICES, default=0)
    hair_color = models.IntegerField(choices=HAIR_COLOR_CHOICES, default=0)
    eye_color = models.IntegerField(choices=EYE_COLOR_CHOICES, default=0)
    body_type = models.IntegerField(choices=BODY_CHOICES, default=0)
    profession = models.IntegerField(choices=PROFESSION_CHOICES, default=0)
    birth_date = models.DateField(blank=True, null=True)
    gender = models.IntegerField(choices=GENDER_CHOICES, default=0)
    safe_mode = models.BooleanField(default=True)
    last_active = models.DateTimeField(blank=True, null=True)

    objects = ProfileManager()

    @models.permalink
    def get_absolute_url(self):
        return ('view_profile', None, {'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.name and self.email:
            self.name = self.email.split("@")[0]
        if not self.slug:
            hsh = hashlib.md5(unicode(datetime_to_epoch(datetime.datetime.now())))
            hsh.update(unicode(random.randint(1, 10**9)))
            self.slug = hsh.hexdigest()
        super(Profile, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.username

    def my_age(self):
        return (datetime.datetime.now().date() - self.birth_date).days/365

    def get_images(self):
        images = [None for i in xrange(9)]
        for i, img in enumerate(self.image_set.all().order_by("-is_avatar", "-upload_date")[:9]):
            images[i] = img
        return images

    def get_avatar(self):
        try:
            return self.image_set.get(is_avatar=True, need_moderation=False)
        except Image.DoesNotExist:
            return
        except Image.MultipleObjectsReturned:
            return  self.image_set.filter(is_avatar=True, need_moderation=False).order_by('-upload_date')[0]

    def is_paid(self):
        return bool(self.subscribe_set.count())

    def is_online_now(self):
        if self.last_active:
            return (datetime.datetime.now() - self.last_active).seconds < 10 * 60
        return False






class Update(models.Model):
    EVENT_TYPE_CHOICES = (
        (0, 'new user'),
        (1, 'uploaded new picture'),
        (2, 'new message'),
        (3, 'changed profile picture'),
    )
    def _get_hash(self):
        if not self.event_date:
            self.event_date = datetime.datetime.now()
        hsh = hashlib.md5(unicode(self.user.id))
        hsh.update(unicode(int(datetime_to_epoch(self.event_date))))
        return hsh.hexdigest()

locations/views.py
from django.http import HttpResponse, HttpReponse404
from django.utils import simplejson
from .models import XCity
from django.db.models import Q
from django.core import serializers
from profiles.forms import LocationForm

templates/profiles/profile_view.html
{% extends "base.html" %}

{% load thumbnail %}

{% block content %}
<style>
.viewEditProfile .top .short-info .name {
    font-size: 24px;
    font-weight: 700;
}
</style>
<div class="viewEditProfile">
    <!-- Start TOP --!>
    <div class="top">
        <div class="short-info">
            <span class="name " id="">{{ profile }}  </span> 
            <span>{{ profile.my_age }}, {{ profile.get_gender_display }}</span>
            {% comment %}
            <span id="safe-mode-chk">
                <label>Safe mode is 
                <span class="on ">on </span>
                <span class="off hidden">off</span>
                </label>
                <input checked="checked" type="checkbox" value="1" name="safeMode" id="safeMode">
            </span>
            {% endcomment %}
        </div>
        <div class="general-info">
        <!-- Images list start --!>
            <div class="images">
                <div class="list">
                    <ul>
                    {% if  profile.get_images %}
                        {% for image in profile.get_images %}
                            <li class="ava {% if forllop.0 %}primary-img{% endif %}">
                                <a href="#{{ forloop.counter }}">
                                    {% thumbnail image.src "100x100" crop="center" as im %}
                                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                                    {% empty %}
                                        <img src="http://images.xdating.com/internal/no_photo_{{ profile.get_gender_display|lower }}_100.png" width="100" height="100">
                                    {% endthumbnail %}
                                </a>
                                <div class="img-tools" style="display: none; ">
                                    <a href="/image/setPrimary/id/2735287" title="" class="set-primary-img">
                                    <span>Primary</span>
                                    </a>
                                    <a href="/image/delete/id/2735287" title="" class="delete-img">
                                    <span>Delete</span>
                                    </a>
                                </div>
                            </li>
                        {% endfor %}
                    {% else %}
                        {% for i in 'emptyImgs' %} {% comment %}  emptyImgs is just a work which contains 9 chars to iterate over them {% endcomment %}
                        <li class="{% if forllop.0 %}primary-img{% endif %}">
                            <a href="#">
                                <img src="http://images.xdating.com/internal/no_photo_{{ profile.gender }}_100.png" width="100" height="100">
                            </a>
                        </li>
                        {% endfor %}
                    {% endif %}
                    </ul>
                </div>    
            </div>
            <!-- Images list end --!>

            <div class="primary">
                <div class="prev-next-links">
                    <div class="area left-area">
                        <a href="#" class="prev-image">Prev</a>
                    </div>
                    <div class="area right-area">
                        <a href="#" class="next-image">Next</a>
                    </div>
                </div>
                <div class="image edit-profile-{{ profile.get_gender_display|capfirst}}">
                    <a href="#" data-index="0">
                    {% if profile.get_avatar %}
                    {% thumbnail profile.get_avatar.src "320x310" crop="center" as big_ava %}
                    <img src="{{ big_ava.url }}" id="gallery-big-image">
                    {% endthumbnail %}
                    {% endif %}
                    </a>
                </div>
                <div class="actions" id="match-actions">
                    {% if request.user.is_authenticated %}
                    {% if not liked_or_not %}
                    <button id="matchRequestSend" class="matchRequest" data-value="send">
                        Like {% if profile.get_gender_display|lower == "man" %}him{% else %}her {% endif %} ?	
                    </button>
                    
                    {% else %}
                    <span class="match-message-text mutual-like">You like {% if profile.get_gender_display|lower == "man" %}him{% else %}her {% endif %} !</span>

                    {% endif %}
                    {% endif %}

                </div>
            </div>
            <!-- Location Start --!>
            {% with not_owner as True %}
            {% include "profiles/_location.html" %}
            {% endwith %}
            <!-- Location End --!>
        </div>
    </div>    
    <!-- end TOP --!> 

<script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
        $('.tabs').tabs();
        });
</script>

<div class="middle">
	<div class="left">
		<div class="tabs tabs-blackBg ui-tabs ui-widget ui-widget-content ui-corner-all">
			<ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
                <li id="big-tab-profile-messages" class="ui-state-default ui-corner-top ui-tabs-selected ui-state-active">
						<a href="#privateMessage">Private Message</a>
				</li>
				<li id="big-tab-profile-updates" class="ui-state-default ui-corner-top">
					<a href="#profileUpdates">Updates</a>
				</li>
			</ul>
            {% include "profiles/send_private_message.html" %}

            {#% with user as profile %#}
            {% include "profiles/profile_updates.html" %}
            {#% endwith %#}
		</div>
	</div>
    <div class="personal-info">
        <div class="tabs ui-tabs ui-widget ui-widget-content ui-corner-all">
		    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
			    <li class="one-small-tab ui-state-default ui-corner-top ui-tabs-selected ui-state-active">
				    <a href="#personalInfo">Personal Information</a>
    			</li>
	    	</ul>
            <div id="personalInfo" class="ui-tabs-panel ui-widget-content ui-corner-bottom">
                <div class="description" id="infoSelfDescription">
                    <p>{{ profile.about_me }}&nbsp;</p>
                </div>
                <div class="list">
                    <dl>
                        <dt>I am seeking:</dt>
                        <dd id="infoLookingFor">{{ profile.get_looking_for_display }}</dd>
                    </dl>
                </div>
                <div class="list">
                    <dl>
                        <dt>Height:</dt>
                            <dd id="infoHeight">{{ profile.get_height_display }}</dd>
                        <dt>Race:</dt>
                            <dd id="infoRace">{{ profile.get_race_display }}</dd>
                    </dl>
                </div>
                <div class="list last">
                    <dl>
                        <dt>Hair Color:</dt>
                            <dd id="infoHairColor">{{ profile.get_hair_color_display }}</dd>
                        <dt>Eye Color:</dt>
                            <dd id="infoEyeColor">{{ profile.get_eye_color_display }}</dd>
                        <dt>Body Type:</dt>
                            <dd id="infoBodyType">{{ profile.get_body_type_display }}</dd>
                        <dt>Profession:</dt>
                            <dd id="infoProfession">{{ profile.get_profession_display }}</dd>
                    </dl>
                </div>
            </div>
		</div>
        <div class="clear"></div>
    </div>
</div>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
        $('.tabs').tabs();
        $('.delete').hide();
        
        $("#matchRequestSend").click(function(){
            var username = $(".short-info .name").text();
            $.get('/matchProcess/',{liked:username},onMatchSuccess, 'json')
            });
        function onMatchSuccess(json){
            if (json.gender == 'him'){
                $('#match-actions').html(
                    '<span class="match-message-text mutual-like"> You like him!</span>');
            } else {
                $('#match-actions').html(
                    '<span class="match-message-text mutual-like"> You like her!</span>');
            }
        }; 
    });
    </script>

{% if not request.user.is_authenticated %}
{% include "sign_up.html" %}
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        var d = $("#registration-tabs").dialog({
            autoOpen: true,
            dialogClass: "landing-search-login",
            buttons: [],
            //dialogClass: "popup-register-login",
            closeOnEscape: true,
            draggable: false,
            width: '450px',
            height: 'auto',
            title: 'Help',
            resizable: false,
            position: 'center',
            modal: true,
        });
        $(".tabs").tabs();
        
        $('#signinForm').submit(function() {
                str = $(this).serialize()
                $.post('{% url auth_login %}', str, function(data) {
                    if (data['saved'] == false){
                        for ( keyVar in data['errors'] ) {
                            if (keyVar == '__all__'){
                                $('#signinForm #error-msg-logform').html('<p class="error-msg">'+data['errors'][keyVar]+'</p>');
                            }
                            else {
                            $('#signinForm #'+keyVar+'_err').html(
                                '<p class="error-msg">'+data['errors'][keyVar]+'</p>'
                                );
                            }
                        }
                    }
                    else
                        if (data['saved'] == true)
                            location.reload();
                }, "json");
                return false;
                });
});
</script>
{% endif %} 

</div> 
{% endblock %}

templates/profiles/search_pages.html
{% load endless %}
{% load statis_pagin %}
{% load thumbnail %}
<ul class="profiles list-view-all search-result-list">
{% comment %}
AJAX PAGINATION IS HERE
{% endcomment %}
{% paginate num users %}
{% for user in users %}
    <li class="profile-search-info last">
        <div class="short-info">
            <span>
                <!-- IE --> </span>
            <a href="{% url view_profile slug=user.slug %}" class="popup">
                <span class="name">{{ user.name }}</span
                            </a>
                <span>{{ user.my_age }}, {{ user.get_gender_display|capfirst }}</span>
                <a href="#linkToPictures">
                    <span class="no-pictures">1</span>
                </a>
            </div>
            <div class="image">
                <a href="{% url view_profile slug=user.slug %}" class="popup">
                    <span>
                        <!-- IE --> </span>
                    {% thumbnail image.src "150x150" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                    {% empty %}
                    <img src="http://images.xdating.com/internal/no_photo_{{ user.get_gender_display|lower }}_150.png" width="150" height="150">
                    {% endthumbnail %}
                    {% comment %}
                    <img src="http://images.xdating.com/ffe0ceefedf5a8ecc2659282466bf5dd.jpg" width="150" height="150">
                    {% endcomment %}
                    <span>
                        <!-- IE --> </span>
                </a>
            </div>
            <div class="location">{{ user.location }}</div>
        </li>
{% endfor %}
</ul>
<div class="clear"></div>

<div class="pagination">
{% get_pages %}
    <ul class >
    {% set_pagin pages 4 %}
    </ul>
</div>